# Generated by Django 2.2.6 on 2019-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='questionId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
