# Generated by Django 2.2.6 on 2019-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_translation_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
