# Generated by Django 2.2.6 on 2019-10-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='regionId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
