# Generated by Django 2.1 on 2020-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_translation_regionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_translated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='progress',
        ),
    ]
