# Generated by Django 2.1 on 2020-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200306_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
