# Generated by Django 2.1 on 2020-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='progress',
            field=models.IntegerField(editable=False),
        ),
    ]
