# Generated by Django 2.1 on 2020-03-16 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200306_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 39, 57, 238907)),
        ),
    ]
