# Generated by Django 2.1 on 2020-03-16 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_translation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 44, 30, 609947)),
        ),
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 16, 44, 30, 609947)),
        ),
    ]
