# Generated by Django 2.1 on 2020-04-10 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200316_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trans_num',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 13, 47, 46, 805099)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 13, 47, 46, 804102)),
        ),
    ]
