# Generated by Django 2.1 on 2020-04-10 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200410_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 14, 0, 57, 450710)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 14, 0, 57, 450710)),
        ),
    ]
