# Generated by Django 2.1 on 2020-05-29 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200410_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='translation',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 55, 31, 762767)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 55, 31, 761770)),
        ),
        migrations.AlterField(
            model_name='user',
            name='trans_num',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
