# Generated by Django 2.1 on 2020-05-29 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200529_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 0, 38, 915399)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 0, 38, 914400)),
        ),
    ]
